<?php

namespace DidUngar\MenuBundle\Entity;

/**
 * MenuLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
